version: "3.7"
services:
  app:
    build:
      context: ./app
    ports:
      - 80:80
    volumes:
      - ./contents:/var/www/html
    links:
      - db
  db:
    image: mysql:5.7
    environment:
      - "MYSQL_DATABASE=sample"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "13306:3306"
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - app
    ports:
      - 4040:80